# Generated by Django 5.2.3 on 2025-07-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_userprofile_email_remove_userprofile_reg_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
