# Generated by Django 5.2.3 on 2025-08-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_userprofile_id_userprofile_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='point',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
