# Generated by Django 5.2.3 on 2025-08-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_point_userprofile_credit_creditpurchase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditpurchase',
            name='charge',
        ),
        migrations.AddField(
            model_name='creditpurchase',
            name='payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='creditpurchase',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
