from django.urls import path
from .views import (
    PlayChatView, 
    PlayChatDetailView, 
    PlayChatChemAnalyzeView, 
    PlayChatSomeAnalyzeView,
    PlayChatMBTIAnalyzeView,
    PlayChemResultDetailView,
    PlaySomeResultDetailView,
    PlayMBTIResultDetailView,
    PlayResultAllView,
    PlayChemQuizView,
    PlayChemQuizQuestionListDetailView,
    PlayChemQuizQuestionListGuestView,
    PlayChemQuizStartView,
    # PlayChemQuizSolveDetailView,
    # PlayChemQuizSubmissionView,
    PlayChemQuizResultListView,
    PlayChemQuizPersonalView,
    PlayChemQuizModifyView,
    PlayChemQuizSubmitView,
    PlaySomeQuizView,
    PlaySomeQuizQuestionListDetailView,
    PlaySomeQuizQuestionListView,
    PlaySomeQuizStartView,
    PlaySomeQuizPersonalView,
    PlaySomeQuizResultListView,
    PlaySomeQuizModifyView,
    PlaySomeQuizSubmitView,
    PlayMBTIQuizView,
    PlayMBTIQuizQuestionListDetailView,
    PlayMBTIQuizQuestionListView,
    PlayMBTIQuizStartView,
    PlayMBTIQuizPersonalView,
    PlayMBTIQuizResultListView,
    PlayMBTIQuizModifyView,
    PlayMBTIQuizSubmitView,
    GenerateUUIDView,
    PlayChemResultDetailViewGuest,
    PlaySomeResultDetailViewGuest,
    PlayMBTIResultDetailViewGuest,
    PlayChemQuizStartGuestView,
    PlayChemQuizSubmitGuestView,
    PlayChemQuizPersonalGuestView,
    PlaySomeQuizStartGuestView,
    PlaySomeQuizSubmitGuestView,
    PlaySomeQuizPersonalGuestView,
    PlayMBTIQuizStartGuestView,
    PlayMBTIQuizSubmitGuestView,
    PlayMBTIQuizPersonalGuestView,
    PlayChemQuizAddView,
    PlaySomeQuizAddView,
    PlayMBTIQuizAddView,
    UuidToTypeView,
)
app_name = 'play'

urlpatterns = [
    path('chat/', PlayChatView.as_view()),
    path('chat/<int:chat_id>/', PlayChatDetailView.as_view()),
    path('chat/<int:chat_id>/analyze/chem/', PlayChatChemAnalyzeView.as_view()),  
    path('chat/<int:chat_id>/analyze/some/', PlayChatSomeAnalyzeView.as_view()),
    path('chat/<int:chat_id>/analyze/mbti/', PlayChatMBTIAnalyzeView.as_view()),  
    path('analysis/chem/<int:result_id>/detail/', PlayChemResultDetailView.as_view()), 
    path('analysis/some/<int:result_id>/detail/', PlaySomeResultDetailView.as_view()), 
    path('analysis/mbti/<int:result_id>/detail/', PlayMBTIResultDetailView.as_view()), 
    path('analysis/all/', PlayResultAllView.as_view()),


    path("chat/uuid/<int:result_id>", GenerateUUIDView.as_view()),
    path("chat/uuid/search/<uuid:uuid>/", UuidToTypeView.as_view()),
    path("analysis/chem/guest/<uuid:uuid>/detail/", PlayChemResultDetailViewGuest.as_view()),
    path("analysis/some/guest/<uuid:uuid>/detail/", PlaySomeResultDetailViewGuest.as_view()),
    path("analysis/mbti/guest/<uuid:uuid>/detail/", PlayMBTIResultDetailViewGuest.as_view()),


    path("quiz/chem/<int:result_id>", PlayChemQuizView.as_view()),
    path("quiz/chem/<uuid:uuid>/questions/", PlayChemQuizQuestionListGuestView.as_view()),
    path("quiz/chem/<int:result_id>/questions/detail/", PlayChemQuizQuestionListDetailView.as_view()),
    path('quiz/chem/<int:result_id>/start/', PlayChemQuizStartView.as_view()),
    path('quiz/chem/<uuid:uuid>/start/guest/', PlayChemQuizStartGuestView.as_view()),
    path('quiz/chem/<int:result_id>/personal/<int:QP_id>/', PlayChemQuizPersonalView.as_view()),
    path('quiz/chem/<uuid:uuid>/personal/guest/<int:QP_id>/', PlayChemQuizPersonalGuestView.as_view()),
    path('quiz/chem/<int:result_id>/result/', PlayChemQuizResultListView.as_view()),
    path('quiz/chem/<int:result_id>/modify/<int:question_index>', PlayChemQuizModifyView.as_view()),
    path('quiz/chem/<int:result_id>/add/', PlayChemQuizAddView.as_view()),
    path('quiz/chem/<int:result_id>/submit/<int:QP_id>', PlayChemQuizSubmitView.as_view()),
    path('quiz/chem/<uuid:uuid>/submit/guest/<int:QP_id>', PlayChemQuizSubmitGuestView.as_view()),


    path("quiz/some/<int:result_id>", PlaySomeQuizView.as_view()),
    path("quiz/some/<uuid:uuid>/questions/", PlaySomeQuizQuestionListView.as_view()),
    path("quiz/some/<int:result_id>/questions/detail/", PlaySomeQuizQuestionListDetailView.as_view()),
    path('quiz/some/<int:result_id>/start/', PlaySomeQuizStartView.as_view()),
    path('quiz/some/<uuid:uuid>/start/guest/', PlaySomeQuizStartGuestView.as_view()),
    path('quiz/some/<int:result_id>/personal/<int:QP_id>/', PlaySomeQuizPersonalView.as_view()),
    path('quiz/some/<uuid:uuid>/personal/guest/<int:QP_id>/', PlaySomeQuizPersonalGuestView.as_view()),
    path('quiz/some/<int:result_id>/result/', PlaySomeQuizResultListView.as_view()),
    path('quiz/some/<int:result_id>/modify/<int:question_index>', PlaySomeQuizModifyView.as_view()),
    path('quiz/some/<int:result_id>/add/', PlaySomeQuizAddView.as_view()),
    path('quiz/some/<int:result_id>/submit/<int:QP_id>', PlaySomeQuizSubmitView.as_view()),
    path('quiz/some/<uuid:uuid>/submit/guest/<int:QP_id>', PlaySomeQuizSubmitGuestView.as_view()),


    path("quiz/mbti/<int:result_id>", PlayMBTIQuizView.as_view()),
    path("quiz/mbti/<uuid:uuid>/questions/", PlayMBTIQuizQuestionListView.as_view()),
    path("quiz/mbti/<int:result_id>/questions/detail/", PlayMBTIQuizQuestionListDetailView.as_view()),
    path('quiz/mbti/<int:result_id>/start/', PlayMBTIQuizStartView.as_view()),
    path('quiz/mbti/<uuid:uuid>/start/guest/', PlayMBTIQuizStartGuestView.as_view()),
    path('quiz/mbti/<int:result_id>/personal/<int:QP_id>/', PlayMBTIQuizPersonalView.as_view()),
    path('quiz/mbti/<uuid:uuid>/personal/guest/<int:QP_id>/', PlayMBTIQuizPersonalGuestView.as_view()),
    path('quiz/mbti/<int:result_id>/result/', PlayMBTIQuizResultListView.as_view()),
    path('quiz/mbti/<int:result_id>/modify/<int:question_index>', PlayMBTIQuizModifyView.as_view()),
    path('quiz/mbti/<int:result_id>/add/', PlayMBTIQuizAddView.as_view()),
    path('quiz/mbti/<int:result_id>/submit/<int:QP_id>', PlayMBTIQuizSubmitView.as_view()),
    path('quiz/mbti/<uuid:uuid>/submit/guest/<int:QP_id>', PlayMBTIQuizSubmitGuestView.as_view()),
]