# Generated by Django 5.2.3 on 2025-07-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='content',
            field=models.FileField(upload_to='chat_files/'),
        ),
    ]
