# Generated by Django 5.2.3 on 2025-07-03 15:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_chat_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultBusContrib',
            fields=[
                ('result_id_bus_contrib', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_saved', models.BooleanField(default=False)),
                ('analysis_date', models.DateField(default=django.utils.timezone.now)),
                ('analysis_type', models.TextField()),
                ('chat_id_bus_contrib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.chat')),
            ],
        ),
    ]
