# Generated by Django 5.2.3 on 2025-07-19 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_resultbuscontrib'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chat_id_bus_contrib',
            new_name='chat_id',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='resultbuscontrib',
            old_name='chat_id_bus_contrib',
            new_name='chat',
        ),
        migrations.RenameField(
            model_name='resultbuscontrib',
            old_name='result_id_bus_contrib',
            new_name='result_id',
        ),
    ]
