# Generated by Django 5.2.3 on 2025-07-20 05:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_rename_chat_id_bus_contrib_chat_chat_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultbuscontrib',
            name='analysis_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ChatBus',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('file', models.FileField(upload_to='chat_files_business/')),
                ('people_num', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='resultbuscontrib',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.chatbus'),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
