# Generated by Django 5.2.3 on 2025-08-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_resultbuscontrib_analysis_date_chatbus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultbuscontrib',
            name='analysis_date',
        ),
        migrations.RemoveField(
            model_name='resultbuscontrib',
            name='analysis_type',
        ),
        migrations.AddField(
            model_name='resultbuscontrib',
            name='analysis_date_end',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resultbuscontrib',
            name='analysis_date_start',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resultbuscontrib',
            name='project_type',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resultbuscontrib',
            name='team_type',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resultbuscontrib',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
