# Generated by Django 5.2.3 on 2025-08-05 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_remove_resultbuscontrib_analysis_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultbuscontrib',
            name='analysis_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
