# Generated by Django 5.2.3 on 2025-08-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_resultbuscontrib_analysis_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultbuscontrib',
            name='people_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultbuscontrib',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
