# Generated by Django 5.2.3 on 2025-08-07 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_resultbuscontrib_people_num_resultbuscontrib_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultbuscontrib',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.chatbus'),
        ),
    ]
