# Generated by Django 5.2.3 on 2025-08-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_remove_resultbuscontrib_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultbuscontrib',
            old_name='analysis_date',
            new_name='created_at',
        ),
    ]
