# Generated by Django 5.2.3 on 2025-08-10 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_rename_analysis_date_resultbuscontrib_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultbuscontrib',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
