# Generated by Django 5.2.3 on 2025-08-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_alter_resultbuscontrib_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultbuscontrib',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
