# Generated by Django 5.2.3 on 2025-08-11 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_resultbuscontrib_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultBusContribSpec',
            fields=[
                ('spec_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_talks', models.IntegerField(default=0)),
                ('leader', models.TextField(default='')),
                ('avg_resp', models.IntegerField(default=0)),
                ('insights', models.TextField(default='')),
                ('recommendation', models.TextField(default='')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.resultbuscontrib')),
            ],
        ),
        migrations.CreateModel(
            name='ResultBusContribSpecPeriod',
            fields=[
                ('specperiod_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('analysis', models.TextField(default='')),
                ('pediod_1', models.IntegerField(default=0)),
                ('period_2', models.IntegerField(default=0)),
                ('period_3', models.IntegerField(default=0)),
                ('period_4', models.IntegerField(default=0)),
                ('period_5', models.IntegerField(default=0)),
                ('period_6', models.IntegerField(default=0)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.resultbuscontribspec')),
            ],
        ),
        migrations.CreateModel(
            name='ResultBusContribSpecPersonal',
            fields=[
                ('specpersonal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('rank', models.IntegerField(default=0)),
                ('participation', models.IntegerField(default=0)),
                ('infoshare', models.IntegerField(default=0)),
                ('probsolve', models.IntegerField(default=0)),
                ('resptime', models.IntegerField(default=0)),
                ('type', models.TextField(default='')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.resultbuscontribspec')),
            ],
        ),
    ]
