# Generated by Django 5.2.3 on 2025-08-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_resultbuscontribspec_resultbuscontribspecperiod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultbuscontribspec',
            name='analysis_size',
            field=models.IntegerField(default=0),
        ),
    ]
