# Generated by Django 5.2.3 on 2025-08-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0016_resultbuscontrib_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultbuscontrib",
            name="num_chat",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resultbuscontribspecpersonal",
            name="proposal",
            field=models.IntegerField(default=0),
        ),
    ]
