# Generated by Django 5.2.3 on 2025-08-19 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_resultbuscontrib_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UuidContrib',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.resultbuscontrib')),
            ],
        ),
    ]
