# Generated by Django 5.2.3 on 2025-08-21 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0017_resultbuscontrib_num_chat_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resultbuscontribspecperiod",
            old_name="pediod_1",
            new_name="period_1",
        ),
    ]
