# Generated by Django 5.2.3 on 2025-08-22 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_uuidcontrib'),
        ('business', '0018_rename_pediod_1_resultbuscontribspecperiod_period_1'),
    ]

    operations = [
    ]
