# Generated by Django 5.2.3 on 2025-08-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_merge_20250822_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultbuscontribspecpersonal',
            name='analysis',
            field=models.TextField(default=''),
        ),
    ]
