# Generated by Django 5.2.3 on 2025-07-03 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatsPlayChem",
            fields=[
                (
                    "chat_id_play_chem",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="채팅번호"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="제목")),
                ("file", models.FileField(upload_to="uploads/", verbose_name="파일")),
                ("people_num", models.IntegerField(verbose_name="사람 수")),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="업로드 시간"
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="유저번호")),
            ],
        ),
    ]
