# Generated by Django 5.2.3 on 2025-08-05 17:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultplaychem',
            name='analysis_type',
        ),
        migrations.AddField(
            model_name='resultplaychem',
            name='analysis_date_end',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resultplaychem',
            name='analysis_date_start',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resultplaychem',
            name='relationship',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resultplaychem',
            name='situation',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resultplaychem',
            name='analysis_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ResultPlayMBTI',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_saved', models.BooleanField(default=False)),
                ('analysis_date_start', models.TextField(default='')),
                ('analysis_date_end', models.TextField(default='')),
                ('analysis_date', models.DateField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.chatplay')),
            ],
        ),
        migrations.CreateModel(
            name='ResultPlaySome',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_saved', models.BooleanField(default=False)),
                ('relationship', models.TextField(default='')),
                ('age', models.TextField(default='')),
                ('analysis_date_start', models.TextField(default='')),
                ('analysis_date_end', models.TextField(default='')),
                ('analysis_date', models.DateField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.chatplay')),
            ],
        ),
    ]
