# Generated by Django 5.2.4 on 2025-07-03 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultPlayChem",
            fields=[
                (
                    "result_id_play_chem",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="결과번호"
                    ),
                ),
                ("content", models.TextField(verbose_name="분석내용")),
                ("is_saved", models.IntegerField(verbose_name="저장여부")),
                (
                    "analysis_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="분석날짜"
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(max_length=100, verbose_name="분석종류"),
                ),
                ("chat_id_play_chem", models.IntegerField(verbose_name="채팅번호")),
            ],
        ),
    ]
