# Generated by Django 5.2.4 on 2025-07-03 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0002_resultplaychem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultplaychem",
            name="chat_id_play_chem",
            field=models.ForeignKey(
                db_column="chat_id_play_chem",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="play.chatsplaychem",
                verbose_name="채팅번호",
            ),
        ),
    ]
