# Generated by Django 5.2.3 on 2025-08-05 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_remove_resultplaychem_analysis_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultplaychem',
            name='analysis_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resultplaymbti',
            name='analysis_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resultplaysome',
            name='analysis_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
