# Generated by Django 5.2.3 on 2025-08-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_alter_resultplaychem_analysis_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultplaychem',
            name='people_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultplaychem',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resultplaymbti',
            name='people_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultplaymbti',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resultplaysome',
            name='people_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultplaysome',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
