# Generated by Django 5.2.3 on 2025-08-07 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0005_alter_resultplaychem_chat_alter_resultplaymbti_chat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultPlaySomeSpec',
            fields=[
                ('spec_id', models.AutoField(primary_key=True, serialize=False)),
                ('score_main', models.IntegerField(default=0)),
                ('comment_main', models.TextField(default='')),
                ('score_A', models.IntegerField(default=0)),
                ('score_B', models.IntegerField(default=0)),
                ('trait_A', models.TextField(default='')),
                ('trait_B', models.TextField(default='')),
                ('summary', models.TextField(default='')),
                ('tone', models.IntegerField(default=0)),
                ('tone_desc', models.TextField(default='')),
                ('tone_ex', models.TextField(default='')),
                ('emo', models.IntegerField(default=0)),
                ('emo_desc', models.TextField(default='')),
                ('emo_ex', models.TextField(default='')),
                ('addr', models.IntegerField(default=0)),
                ('addr_desc', models.TextField(default='')),
                ('addr_ex', models.TextField(default='')),
                ('reply_A', models.IntegerField(default=0)),
                ('reply_B', models.IntegerField(default=0)),
                ('reply_A_desc', models.TextField(default='')),
                ('reply_B_desc', models.TextField(default='')),
                ('rec_A', models.IntegerField(default=0)),
                ('rec_B', models.IntegerField(default=0)),
                ('rec_A_desc', models.TextField(default='')),
                ('rec_B_desc', models.TextField(default='')),
                ('rec_A_ex', models.TextField(default='')),
                ('rec_B_ex', models.TextField(default='')),
                ('atti_A', models.IntegerField(default=0)),
                ('atti_B', models.IntegerField(default=0)),
                ('atti_A_desc', models.TextField(default='')),
                ('atti_B_desc', models.TextField(default='')),
                ('atti_A_ex', models.TextField(default='')),
                ('atti_B_ex', models.TextField(default='')),
                ('pattern_analysis', models.TextField(default='')),
                ('chatto_coundel', models.TextField(default='')),
                ('chatto_coundel_tips', models.TextField(default='')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.resultplaysome')),
            ],
        ),
    ]
