# Generated by Django 5.2.3 on 2025-08-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0006_resultplaysomespec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultplaychem',
            name='content',
        ),
        migrations.RemoveField(
            model_name='resultplaymbti',
            name='content',
        ),
        migrations.RemoveField(
            model_name='resultplaysome',
            name='content',
        ),
    ]
