# Generated by Django 5.2.3 on 2025-08-07 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0007_remove_resultplaychem_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultPlayMBTISpec',
            fields=[
                ('spec_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_I', models.IntegerField(default=0)),
                ('total_E', models.IntegerField(default=0)),
                ('total_S', models.IntegerField(default=0)),
                ('total_N', models.IntegerField(default=0)),
                ('total_F', models.IntegerField(default=0)),
                ('total_T', models.IntegerField(default=0)),
                ('total_J', models.IntegerField(default=0)),
                ('total_P', models.IntegerField(default=0)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.resultplaymbti')),
            ],
        ),
        migrations.CreateModel(
            name='ResultPlayMBTISpecPersonal',
            fields=[
                ('specpersonal_id', models.AutoField(primary_key=True, serialize=False)),
                ('MBTI', models.TextField(default='')),
                ('summary', models.TextField(default='')),
                ('desc', models.TextField(default='')),
                ('position', models.TextField(default='')),
                ('personality', models.TextField(default='')),
                ('style', models.TextField(default='')),
                ('moment_ex', models.TextField(default='')),
                ('moment_desc', models.TextField(default='')),
                ('momentIE_ex', models.TextField(default='')),
                ('momentIE_desc', models.TextField(default='')),
                ('momentSN_ex', models.TextField(default='')),
                ('momentSN_desc', models.TextField(default='')),
                ('momentFT_ex', models.TextField(default='')),
                ('momentFT_desc', models.TextField(default='')),
                ('momentJP_ex', models.TextField(default='')),
                ('momentJP_desc', models.TextField(default='')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.resultplaymbtispec')),
            ],
        ),
    ]
