# Generated by Django 5.2.3 on 2025-08-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0008_resultplaymbtispec_resultplaymbtispecpersonal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultplaychem',
            old_name='analysis_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='resultplaymbti',
            old_name='analysis_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='resultplaysome',
            old_name='analysis_date',
            new_name='created_at',
        ),
    ]
