# Generated by Django 5.2.3 on 2025-08-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0009_rename_analysis_date_resultplaychem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultplaychem',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultplaymbti',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultplaysome',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
