# Generated by Django 5.2.3 on 2025-08-11 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0010_resultplaychem_type_resultplaymbti_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultPlayChemSpec',
            fields=[
                ('spec_id', models.AutoField(primary_key=True, serialize=False)),
                ('score_main', models.IntegerField(default=0)),
                ('summary_main', models.TextField(default='')),
                ('top1_A', models.TextField(default='')),
                ('top1_B', models.TextField(default='')),
                ('top1_score', models.IntegerField(default=0)),
                ('top1_comment', models.TextField(default='')),
                ('top2_A', models.TextField(default='')),
                ('top2_B', models.TextField(default='')),
                ('top2_score', models.IntegerField(default=0)),
                ('top2_comment', models.TextField(default='')),
                ('top3_A', models.TextField(default='')),
                ('top3_B', models.TextField(default='')),
                ('top3_score', models.IntegerField(default=0)),
                ('top3_comment', models.TextField(default='')),
                ('tone_pos', models.IntegerField(default=0)),
                ('tone_humer', models.IntegerField(default=0)),
                ('tone_else', models.IntegerField(default=0)),
                ('tone_ex', models.TextField(default='')),
                ('resp_time', models.IntegerField(default=0)),
                ('resp_ratio', models.IntegerField(default=0)),
                ('ignore', models.IntegerField(default=0)),
                ('resp_analysis', models.TextField(default='')),
                ('topic1', models.TextField(default='')),
                ('topic1_ratio', models.IntegerField(default=0)),
                ('topic2', models.TextField(default='')),
                ('topic2_ratio', models.IntegerField(default=0)),
                ('topic3', models.TextField(default='')),
                ('topic3_ratio', models.IntegerField(default=0)),
                ('topic4', models.TextField(default='')),
                ('topic4_ratio', models.IntegerField(default=0)),
                ('topicelse_ratio', models.IntegerField(default=0)),
                ('chatto_analysis', models.TextField(default='')),
                ('chatto_levelup', models.TextField(default='')),
                ('chatto_levelup_tips', models.TextField(default='')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.resultplaychem')),
            ],
        ),
        migrations.CreateModel(
            name='ResultPlayChemSpecTable',
            fields=[
                ('spectable_id', models.AutoField(primary_key=True, serialize=False)),
                ('row', models.IntegerField(default=0)),
                ('column', models.IntegerField(default=0)),
                ('interaction', models.IntegerField(default=0)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.resultplaychemspec')),
            ],
        ),
    ]
