# Generated by Django 5.2.3 on 2025-08-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0011_resultplaychemspec_resultplaychemspectable'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultplaychemspec',
            name='tablesize',
            field=models.IntegerField(default=0),
        ),
    ]
