# Generated by Django 5.2.3 on 2025-08-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0012_resultplaychemspec_tablesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultplaymbtispecpersonal',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
