# Generated by Django 5.2.3 on 2025-08-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0013_resultplaymbtispecpersonal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultplaychemspec',
            name='name_0',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resultplaychemspec',
            name='name_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resultplaychemspec',
            name='name_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resultplaychemspec',
            name='name_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resultplaychemspec',
            name='name_4',
            field=models.TextField(default=''),
        ),
    ]
