# Generated by Django 5.2.3 on 2025-08-13 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0014_resultplaychemspec_name_0_resultplaychemspec_name_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemQuiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_num', models.IntegerField(default=0)),
                ('solved_num', models.IntegerField(default=0)),
                ('avg_score', models.IntegerField(default=0)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.resultplaychem')),
            ],
        ),
        migrations.CreateModel(
            name='ChemQuizPersonal',
            fields=[
                ('QP_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('score', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.chemquiz')),
            ],
        ),
        migrations.CreateModel(
            name='ChemQuizQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(default='')),
                ('choice1', models.TextField(default='')),
                ('choice2', models.TextField(default='')),
                ('choice3', models.TextField(default='')),
                ('choice4', models.TextField(default='')),
                ('answer', models.IntegerField(default=0)),
                ('count1', models.IntegerField(default=0)),
                ('count2', models.IntegerField(default=0)),
                ('count3', models.IntegerField(default=0)),
                ('count4', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.chemquiz')),
            ],
        ),
        migrations.CreateModel(
            name='ChemQuizPersonalDetail',
            fields=[
                ('QPD_id', models.AutoField(primary_key=True, serialize=False)),
                ('responce', models.IntegerField(default=0)),
                ('result', models.BooleanField(default=False)),
                ('QP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.chemquizpersonal')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.chemquizquestion')),
            ],
        ),
        migrations.CreateModel(
            name='MBTIQuiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_num', models.IntegerField(default=0)),
                ('solved_num', models.IntegerField(default=0)),
                ('avg_score', models.IntegerField(default=0)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.resultplaymbti')),
            ],
        ),
        migrations.CreateModel(
            name='MBTIQuizPersonal',
            fields=[
                ('QP_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('score', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.mbtiquiz')),
            ],
        ),
        migrations.CreateModel(
            name='MBTIQuizQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(default='')),
                ('choice1', models.TextField(default='')),
                ('choice2', models.TextField(default='')),
                ('choice3', models.TextField(default='')),
                ('choice4', models.TextField(default='')),
                ('answer', models.IntegerField(default=0)),
                ('count1', models.IntegerField(default=0)),
                ('count2', models.IntegerField(default=0)),
                ('count3', models.IntegerField(default=0)),
                ('count4', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.mbtiquiz')),
            ],
        ),
        migrations.CreateModel(
            name='MBTIQuizPersonalDetail',
            fields=[
                ('QPD_id', models.AutoField(primary_key=True, serialize=False)),
                ('responce', models.IntegerField(default=0)),
                ('result', models.BooleanField(default=False)),
                ('QP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.mbtiquizpersonal')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.mbtiquizquestion')),
            ],
        ),
        migrations.CreateModel(
            name='SomeQuiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_num', models.IntegerField(default=0)),
                ('solved_num', models.IntegerField(default=0)),
                ('avg_score', models.IntegerField(default=0)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.resultplaysome')),
            ],
        ),
        migrations.CreateModel(
            name='SomeQuizPersonal',
            fields=[
                ('QP_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('score', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.somequiz')),
            ],
        ),
        migrations.CreateModel(
            name='SomeQuizQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(default='')),
                ('choice1', models.TextField(default='')),
                ('choice2', models.TextField(default='')),
                ('choice3', models.TextField(default='')),
                ('choice4', models.TextField(default='')),
                ('answer', models.IntegerField(default=0)),
                ('count1', models.IntegerField(default=0)),
                ('count2', models.IntegerField(default=0)),
                ('count3', models.IntegerField(default=0)),
                ('count4', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.somequiz')),
            ],
        ),
        migrations.CreateModel(
            name='SomeQuizPersonalDetail',
            fields=[
                ('QPD_id', models.AutoField(primary_key=True, serialize=False)),
                ('responce', models.IntegerField(default=0)),
                ('result', models.BooleanField(default=False)),
                ('QP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.somequizpersonal')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.somequizquestion')),
            ],
        ),
    ]
