# Generated by Django 5.2.3 on 2025-08-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0015_chemquiz_chemquizpersonal_chemquizquestion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemquizpersonaldetail',
            old_name='responce',
            new_name='response',
        ),
        migrations.AddField(
            model_name='chemquizquestion',
            name='correct_num',
            field=models.IntegerField(default=0),
        ),
    ]
