# Generated by Django 5.2.3 on 2025-08-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0016_rename_responce_chemquizpersonaldetail_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemquizquestion',
            name='question_index',
            field=models.IntegerField(default=0),
        ),
    ]
