# Generated by Django 5.2.3 on 2025-08-15 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0017_chemquizquestion_question_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbtiquizquestion',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='mbtiquizpersonal',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='mbtiquizpersonaldetail',
            name='QP',
        ),
        migrations.RemoveField(
            model_name='mbtiquizpersonaldetail',
            name='question',
        ),
        migrations.RemoveField(
            model_name='somequiz',
            name='result',
        ),
        migrations.RemoveField(
            model_name='somequizpersonal',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='somequizquestion',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='somequizpersonaldetail',
            name='QP',
        ),
        migrations.RemoveField(
            model_name='somequizpersonaldetail',
            name='question',
        ),
        migrations.AlterField(
            model_name='chemquiz',
            name='result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='play.resultplaychem'),
        ),
        migrations.DeleteModel(
            name='MBTIQuiz',
        ),
        migrations.DeleteModel(
            name='MBTIQuizPersonal',
        ),
        migrations.DeleteModel(
            name='MBTIQuizPersonalDetail',
        ),
        migrations.DeleteModel(
            name='MBTIQuizQuestion',
        ),
        migrations.DeleteModel(
            name='SomeQuiz',
        ),
        migrations.DeleteModel(
            name='SomeQuizPersonal',
        ),
        migrations.DeleteModel(
            name='SomeQuizPersonalDetail',
        ),
        migrations.DeleteModel(
            name='SomeQuizQuestion',
        ),
    ]
