# Generated by Django 5.2.3 on 2025-08-16 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0019_somequiz_somequizpersonal_somequizquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBTIQuiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_num', models.IntegerField(default=0)),
                ('solved_num', models.IntegerField(default=0)),
                ('avg_score', models.IntegerField(default=0)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='play.resultplaymbti')),
            ],
        ),
        migrations.CreateModel(
            name='MBTIQuizPersonal',
            fields=[
                ('QP_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('score', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.mbtiquiz')),
            ],
        ),
        migrations.CreateModel(
            name='MBTIQuizQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_index', models.IntegerField(default=0)),
                ('question', models.TextField(default='')),
                ('choice1', models.TextField(default='')),
                ('choice2', models.TextField(default='')),
                ('choice3', models.TextField(default='')),
                ('choice4', models.TextField(default='')),
                ('answer', models.IntegerField(default=0)),
                ('correct_num', models.IntegerField(default=0)),
                ('count1', models.IntegerField(default=0)),
                ('count2', models.IntegerField(default=0)),
                ('count3', models.IntegerField(default=0)),
                ('count4', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.mbtiquiz')),
            ],
        ),
        migrations.CreateModel(
            name='MBTIQuizPersonalDetail',
            fields=[
                ('QPD_id', models.AutoField(primary_key=True, serialize=False)),
                ('response', models.IntegerField(default=0)),
                ('result', models.BooleanField(default=False)),
                ('QP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.mbtiquizpersonal')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.mbtiquizquestion')),
            ],
        ),
    ]
