# Generated by Django 5.2.3 on 2025-08-16 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0020_mbtiquiz_mbtiquizpersonal_mbtiquizquestion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultplaysomespec',
            old_name='chatto_coundel',
            new_name='chatto_counsel',
        ),
        migrations.RenameField(
            model_name='resultplaysomespec',
            old_name='chatto_coundel_tips',
            new_name='chatto_counsel_tips',
        ),
    ]
