# Generated by Django 5.2.3 on 2025-08-16 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0021_rename_chatto_coundel_resultplaysomespec_chatto_counsel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultplaychem',
            name='chat',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='play.chatplay'),
        ),
        migrations.AlterField(
            model_name='resultplaymbti',
            name='chat',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='play.chatplay'),
        ),
        migrations.AlterField(
            model_name='resultplaysome',
            name='chat',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='play.chatplay'),
        ),
    ]
