# Generated by Django 5.2.3 on 2025-08-16 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0022_alter_resultplaychem_chat_alter_resultplaymbti_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultplaychem',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='play.chatplay'),
        ),
        migrations.AlterField(
            model_name='resultplaymbti',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='play.chatplay'),
        ),
        migrations.AlterField(
            model_name='resultplaysome',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='play.chatplay'),
        ),
    ]
