# Generated by Django 5.2.3 on 2025-08-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0023_resultplaysomespec_len_a_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultplaychem",
            name="num_chat",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resultplaymbti",
            name="num_chat",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resultplaysome",
            name="num_chat",
            field=models.IntegerField(default=0),
        ),
    ]
