# Generated by Django 5.2.3 on 2025-08-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0024_resultplaychem_user_resultplaymbti_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultplaysomespec',
            name='name_A',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resultplaysomespec',
            name='name_B',
            field=models.TextField(default=''),
        ),
    ]
