# Generated by Django 5.2.3 on 2025-08-18 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0024_resultplaychem_user_resultplaymbti_user_and_more'),
        ('play', '0024_resultplaychem_num_chat_resultplaymbti_num_chat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UuidChem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='play.resultplaychem')),
            ],
        ),
        migrations.CreateModel(
            name='UuidMBTI',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='play.resultplaymbti')),
            ],
        ),
        migrations.CreateModel(
            name='UuidSome',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='play.resultplaysome')),
            ],
        ),
    ]
