# Generated by Django 5.2.3 on 2025-08-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0025_uuidchem_uuidmbti_uuidsome"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultplaychemspec",
            name="tone_crit",
            field=models.IntegerField(default=0),
        ),
    ]
