# Generated by Django 5.2.3 on 2025-08-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0025_resultplaysomespec_name_a_resultplaysomespec_name_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultplaysomespec',
            name='len_A',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultplaysomespec',
            name='len_A_desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resultplaysomespec',
            name='len_A_ex',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resultplaysomespec',
            name='len_B',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultplaysomespec',
            name='len_B_desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resultplaysomespec',
            name='len_B_ex',
            field=models.TextField(default=''),
        ),
    ]
