# Generated by Django 5.2.3 on 2025-08-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0026_resultplaychemspec_tone_crit"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultplaymbtispec",
            name="enfj",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resultplaymbtispec",
            name="enfp",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resultplaymbtispec",
            name="entj",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resultplaymbtispec",
            name="entp",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resultplaymbtispec",
            name="esfj",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resultplaymbtispec",
            name="esfp",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resultplaymbtispec",
            name="estj",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resultplaymbtispec",
            name="estp",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resultplaymbtispec",
            name="infj",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resultplaymbtispec",
            name="infp",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resultplaymbtispec",
            name="intj",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resultplaymbtispec",
            name="intp",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resultplaymbtispec",
            name="isfj",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resultplaymbtispec",
            name="isfp",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resultplaymbtispec",
            name="istj",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resultplaymbtispec",
            name="istp",
            field=models.IntegerField(default=0),
        ),
    ]
