# Generated by Django 5.2.3 on 2025-08-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0026_resultplaychemspec_tone_crit'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultplaychem',
            name='is_quized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultplaymbti',
            name='is_quized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultplaysome',
            name='is_quized',
            field=models.BooleanField(default=False),
        ),
    ]
