# Generated by Django 5.2.3 on 2025-08-21 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0027_resultplaymbtispec_enfj_resultplaymbtispec_enfp_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resultplaymbtispec",
            old_name="enfj",
            new_name="cnt_ENFJ",
        ),
        migrations.RenameField(
            model_name="resultplaymbtispec",
            old_name="enfp",
            new_name="cnt_ENFP",
        ),
        migrations.RenameField(
            model_name="resultplaymbtispec",
            old_name="entj",
            new_name="cnt_ENTJ",
        ),
        migrations.RenameField(
            model_name="resultplaymbtispec",
            old_name="entp",
            new_name="cnt_ENTP",
        ),
        migrations.RenameField(
            model_name="resultplaymbtispec",
            old_name="esfj",
            new_name="cnt_ESFJ",
        ),
        migrations.RenameField(
            model_name="resultplaymbtispec",
            old_name="esfp",
            new_name="cnt_ESFP",
        ),
        migrations.RenameField(
            model_name="resultplaymbtispec",
            old_name="estj",
            new_name="cnt_ESTJ",
        ),
        migrations.RenameField(
            model_name="resultplaymbtispec",
            old_name="estp",
            new_name="cnt_ESTP",
        ),
        migrations.RenameField(
            model_name="resultplaymbtispec",
            old_name="infj",
            new_name="cnt_INFJ",
        ),
        migrations.RenameField(
            model_name="resultplaymbtispec",
            old_name="infp",
            new_name="cnt_INFP",
        ),
        migrations.RenameField(
            model_name="resultplaymbtispec",
            old_name="intj",
            new_name="cnt_INTJ",
        ),
        migrations.RenameField(
            model_name="resultplaymbtispec",
            old_name="intp",
            new_name="cnt_INTP",
        ),
        migrations.RenameField(
            model_name="resultplaymbtispec",
            old_name="isfj",
            new_name="cnt_ISFJ",
        ),
        migrations.RenameField(
            model_name="resultplaymbtispec",
            old_name="isfp",
            new_name="cnt_ISFP",
        ),
        migrations.RenameField(
            model_name="resultplaymbtispec",
            old_name="istj",
            new_name="cnt_ISTJ",
        ),
        migrations.RenameField(
            model_name="resultplaymbtispec",
            old_name="istp",
            new_name="cnt_ISTP",
        ),
    ]
