# Generated by Django 5.2.3 on 2025-08-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0027_resultplaychem_is_quized_resultplaymbti_is_quized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultplaychemspec',
            name='tone_analysis',
            field=models.TextField(default=''),
        ),
    ]
