# Generated by Django 5.2.3 on 2025-08-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0028_resultplaychemspec_tone_analysis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultplaychemspec',
            old_name='tone_ex',
            new_name='tone_ex1',
        ),
        migrations.AddField(
            model_name='resultplaychemspec',
            name='tone_ex2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resultplaychemspec',
            name='tone_ex3',
            field=models.TextField(default=''),
        ),
    ]
