# Generated by Django 5.2.3 on 2025-08-22 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0028_rename_enfj_resultplaymbtispec_cnt_enfj_and_more'),
        ('play', '0029_rename_tone_ex_resultplaychemspec_tone_ex1_and_more'),
    ]

    operations = [
    ]
