# Generated by Django 5.2.3 on 2025-08-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0030_merge_20250822_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemquizpersonaldetail',
            name='answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mbtiquizpersonaldetail',
            name='answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='somequizpersonaldetail',
            name='answer',
            field=models.IntegerField(default=0),
        ),
    ]
