# Generated by Django 5.2.3 on 2025-08-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0031_chemquizpersonaldetail_answer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resultplaychemspec",
            old_name="chatto_levelup",
            new_name="chatto_levelup1",
        ),
        migrations.RenameField(
            model_name="resultplaychemspec",
            old_name="chatto_levelup_tips",
            new_name="chatto_levelup_tips1",
        ),
        migrations.AddField(
            model_name="resultplaychemspec",
            name="chatto_levelup2",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="resultplaychemspec",
            name="chatto_levelup3",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="resultplaychemspec",
            name="chatto_levelup_tips2",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="resultplaychemspec",
            name="chatto_levelup_tips3",
            field=models.TextField(default=""),
        ),
    ]
